main: net.thetowncraft.townbot.Plugin
name: MinecordBot
version: 1.0
author: CadenKoehl
commands:
  mute:
    description: Chat-mutes a player
    usage: /unmute <player>

  unmute:
    description: Un-chat-mutes a player
    usage: /unmute <player>

  active:
    description: See the top 3 most active players!

  pay:
    description: Pay a player a certain amount of coins!
    usage: /pay <player> <amount>

  bal:
    description: See your coin balance!
    usage: /balance <player>

  baltop:
    description: View the economy leaderboard!