main: net.thetowncraft.townbot.Plugin
name: MinecordBot
version: 1.0
author: CadenKoehl
api-version: 1.13
commands:
  mute:
    description: Chat-mutes a player
    usage: /unmute <player>

  unmute:
    description: Un-chat-mutes a player
    usage: /unmute <player>

  active:
    description: See the top 3 most active players!

  pay:
    description: Pay a player a certain amount of coins!
    usage: /pay <player> <amount>

  bal:
    description: See your coin balance!
    usage: /balance <player>

  baltop:
    description: View the economy leaderboard!

  shopchest:
    description: Create a safe and secure shop, that can't be stolen from! (you must be looking at the block that the shop will be placed on)
    usage: /shopchest <price per item> <per stack?(true or false)>

  gci:
    description: Give yourself a custom item
    usage: /gci <item_name> <amount>

  maintenance:
    description: Turn server maintenance on and off